name: CustomPlayerDrop
version: 2.0.0
main: CustomPlayerDrop.Sandrix.Dev.Main
api-version: '1.21'

authors: [Sandrix33, bsbl-ML]
description: Revised plugin for custom player drop (Celestiql SMP)

commands:
  customplayerdrop:
    description: Command to reload config
    usage: /customplayerdrop reload
    permission: customplayerdrop.admin

permissions:
  customplayerdrop.admin:
    description: Allows access to CustomPlayerDrop administrative commands
    default: op
