name: CustomPlayerDrop
version: 2.0.0
main: CustomPlayerDrop.Sandrix.Dev.Main
api-version: '1.21'

authors: [Sandrix33, bsbl-ML]
description: Revised plugin for custom player drop (Celestiql SMP)

commands:
  CustomPlayerDrop:
    description: Command to reload config
    usage: /CustomPlayerDrop reload
    permission: CustomPlayerDrop.admin

permissions:
  CustomPlayerDrop.admin:
    description: Allows access to CustomPlayerDrop administrative commands
    default: op
